# Generated by Django 2.1.3 on 2018-11-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='files',
            field=models.ImageField(upload_to='', verbose_name='文件'),
        ),
    ]
