# Generated by Django 2.1.3 on 2018-12-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advprogrammerelated',
            old_name='time_choice',
            new_name='interval',
        ),
    ]
