# Generated by Django 2.1.3 on 2018-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20181112_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.AlterField(
            model_name='material',
            name='files',
            field=models.ImageField(upload_to='', verbose_name='图片'),
        ),
    ]
