# Generated by Django 2.1.3 on 2018-12-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_advprogrammerelated_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advprogrammerelated',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.AdvProgramme'),
        ),
    ]
