# Generated by Django 2.1.3 on 2018-12-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20181213_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarywelfareprogrammematerial',
            name='play_time',
            field=models.PositiveIntegerField(default=10, help_text='单位/秒', verbose_name='播放时间'),
        ),
    ]
