# Generated by Django 2.1.3 on 2018-12-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20181207_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advprogrammerelated',
            name='title',
        ),
        migrations.AlterField(
            model_name='advprogrammerelated',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.AdvProgramme'),
        ),
    ]
