# Generated by Django 2.1.3 on 2018-11-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20181123_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='is_review',
            field=models.BooleanField(default=False, verbose_name='是否提交审核'),
        ),
    ]
