# Generated by Django 2.1.3 on 2018-12-21 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20181221_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '设备模板',
                'verbose_name': '设备模板',
            },
        ),
        migrations.CreateModel(
            name='MachineTemplateMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialFiles')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MachineTemplate')),
            ],
            options={
                'verbose_name_plural': '设备模板素材',
                'verbose_name': '设备模板素材',
            },
        ),
        migrations.CreateModel(
            name='MachineTemplateRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Machine')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MachineTemplate')),
            ],
            options={
                'verbose_name_plural': '设备模板关联设备',
                'verbose_name': '设备模板关联设备',
            },
        ),
        migrations.AlterUniqueTogether(
            name='machinetemplaterelated',
            unique_together={('machine', 'programme')},
        ),
    ]
