# Generated by Django 2.1.3 on 2018-11-12 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20181112_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetag',
            options={'verbose_name': '文件标签', 'verbose_name_plural': '文件标签'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '图片标签', 'verbose_name_plural': '图片标签'},
        ),
        migrations.AddField(
            model_name='programme',
            name='material_files',
            field=models.ManyToManyField(blank=True, to='materials.MaterialFiles'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
