# Generated by Django 2.1.3 on 2018-11-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_programme_is_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_manage',
            field=models.BooleanField(default=False, verbose_name='管理员'),
        ),
    ]
