# Generated by Django 2.1.3 on 2018-12-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20181207_1628'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advprogrammerelated',
            unique_together={('machine', 'programme')},
        ),
    ]
