# Generated by Django 2.1.3 on 2018-11-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('materials', '0006_userinfo_is_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
