# Generated by Django 2.1.3 on 2018-11-12 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20181112_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='programme',
            name='interval',
        ),
        migrations.AddField(
            model_name='programme',
            name='interval',
            field=models.ManyToManyField(blank=True, to='materials.IntervalTime'),
        ),
    ]
