# Generated by Django 2.1.3 on 2018-11-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_area_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='是否已选择'),
        ),
    ]
