# Generated by Django 2.1.3 on 2018-12-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_advprogrammerelated_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='advprogrammematerial',
            name='play_time',
            field=models.PositiveIntegerField(default=10, help_text='单位/秒', verbose_name='播放时间'),
        ),
        migrations.AddField(
            model_name='primarywelfareprogrammematerial',
            name='play_time',
            field=models.PositiveIntegerField(default=10, help_text='单位/秒', verbose_name='播放时间'),
        ),
        migrations.AddField(
            model_name='secondarywelfareprogrammematerial',
            name='play_time',
            field=models.PositiveIntegerField(default=10, help_text='单位/秒', verbose_name='播放时间'),
        ),
    ]
