# Generated by Django 2.1.3 on 2018-11-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20181112_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.PositiveIntegerField(verbose_name='序号')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.MaterialFiles')),
            ],
            options={
                'verbose_name_plural': '节目单素材',
                'verbose_name': '节目单素材',
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='material',
            name='user',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='files',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='programmematerial',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Programme'),
        ),
    ]
