# Generated by Django 2.1.3 on 2018-11-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20181112_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='material_files',
        ),
        migrations.RemoveField(
            model_name='programmematerial',
            name='programme',
        ),
        migrations.AddField(
            model_name='programme',
            name='materials_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.ProgrammeMaterial'),
        ),
        migrations.AlterField(
            model_name='programmematerial',
            name='nid',
            field=models.PositiveIntegerField(help_text='用来排序', verbose_name='序号'),
        ),
    ]
