# Generated by Django 2.1.3 on 2018-11-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_area_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervaltime',
            name='user',
        ),
    ]
