# Generated by Django 2.1.3 on 2018-11-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20181113_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='materials_related',
        ),
        migrations.AddField(
            model_name='programmematerial',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Programme'),
        ),
        migrations.AlterField(
            model_name='programmematerial',
            name='nid',
            field=models.PositiveIntegerField(verbose_name='序号'),
        ),
    ]
