# Generated by Django 2.1.3 on 2018-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_remove_intervaltime_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='is_publish',
        ),
        migrations.AddField(
            model_name='areaintervaltime',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
    ]
