# Generated by Django 2.1.3 on 2018-11-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20181113_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='interval',
        ),
        migrations.AddField(
            model_name='intervaltime',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Programme'),
        ),
    ]
