# Generated by Django 2.1.3 on 2018-11-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_auto_20181113_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervaltime',
            name='programme',
        ),
        migrations.AddField(
            model_name='programme',
            name='interval',
            field=models.ManyToManyField(blank=True, to='materials.IntervalTime'),
        ),
    ]
